from django.urls import path
from . import views

app_name = 'manager'

urlpatterns = [
    path('', views.index, name= "index"),
    path('add_absence', views.AbsenceModalView.as_view(), name='add_absence'),
    path('add_grade', views.GradeModalView.as_view(), name='add_grade'),
    path('add_substitution', views.Create_SubstitutionModalView.as_view(), name='add_substitution'),
    path('change_password', views.change_password, name= "change_password"),
    path('choose_class', views.choose_class, name= "choose_class"),
    path('choose_grade_class', views.choose_grade_class, name= "choose_grade_class"),
    path('class_timetable', views.class_timetable, name= "class_timetable"),
    path('create_assignment', views.AssignmentModalView.as_view(), name='create_assignment'),
    path('create_classes', views.create_classes, name= "create_classes"),
    path('create_classroom', views.create_classroom, name= "create_classroom"),
    path('create_timetable', views.Students_timetableModalView.as_view(), name='create_timetable'),
    path('dashboard/<int:year_number>/<int:week_number>', views.dashboard, name= "dashboard"),
    path('delete_absence/<int:pk>', views.Absence_DeleteView.as_view(), name='delete_absence'),
    path('delete_assignment/<int:pk>', views.Assignment_DeleteView.as_view(), name='delete_assignment'),
    path('delete_grade/<int:pk>', views.Grade_DeleteView.as_view(), name='delete_grade'),
    path('delete_student/<int:pk>', views.Student_DeleteView.as_view(), name='delete_student'),
    path('delete_sub/<int:pk>', views.Substitution_DeleteView.as_view(), name='delete_sub'),
    path('delete_teacher/<int:pk>', views.Teacher_DeleteView.as_view(), name='delete_teacher'),
    path('delete_tt_element/<int:pk>', views.Timetable_elementDeleteView.as_view(), name='delete_tt_element'),
    path('edit_absence/<int:pk>', views.Absence_updateView.as_view(), name= "edit_absence"),
    path('edit_assignment/<int:pk>', views.Assignment_updateView.as_view(), name= "edit_assignment"),
    path('edit_grade/<int:pk>', views.Grade_updateView.as_view(), name= "edit_grade"),
    path('edit_student/<int:pk>', views.Student_updateView.as_view(), name= "edit_student"),
    path('edit_sub/<int:pk>', views.Substitution_updateView.as_view(), name= "edit_sub"),
    path('edit_teacher/<int:pk>', views.Teacher_updateView.as_view(), name= "edit_teacher"),
    path('grade/<int:pk>', views.Grade_modalView.as_view(), name= "grade_modal"),
    path('login', views.login_view, name="login_view"),
    path('logout', views.logout_view, name= "logout"),
    path('notice/<int:pk>', views.Notice_modalView.as_view(), name= "notice_modal"),
    path('reg_tt_ele/<int:pk>', views.Regular_tt_element_modalView.as_view(), name= "reg_tt_ele"),
    path('register_student', views.register_student, name="register_student"),
    path('register_teacher', views.register_teacher, name="register_teacher"),
    path('s_grades', views.s_grades, name="s_grades"),
    path('student_assignments', views.S_AssignmentsListView.as_view(), name= "student_assignments"),
    path('students_list', views.StudentsListView.as_view(), name= "students_list"),
    path('substitutions', views.SubstitutionsListView.as_view(), name= "substitutions"),
    path('t_grades', views.t_grades, name="t_grades"),
    path('t_notices', views.t_notices, name="t_notices"),
    path('teacher_assignments', views.T_AssignmentsListView.as_view(), name= "teacher_assignments"),
    path('teachers_list', views.TeachersListView.as_view(), name= "teachers_list"),
    path('timetable/<int:student_which_class>/<int:year_number>/<int:week_number>', views.timetable, name= "timetable"),
    path('view_absence/<int:pk>', views.Absence_modalView.as_view(), name= "view_absence"),
    path('view_assignment/<int:pk>', views.Assignment_modalView.as_view(), name= "view_assignment"),
    path('view_student/<int:pk>', views.Student_modalView.as_view(), name= "view_student"),
    path('view_teacher/<int:pk>', views.Teacher_modalView.as_view(), name= "view_teacher"),
]