# Generated by Django 4.1.1 on 2022-09-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='class_supervised',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.classes', unique=True),
        ),
    ]
