# Generated by Django 4.1.1 on 2022-09-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_classes_name_alter_teachers_class_supervised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
