# Generated by Django 4.1.1 on 2022-09-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_timetable_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrooms',
            name='occupied',
        ),
    ]
