# Generated by Django 4.1.1 on 2022-09-09 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_timetable_element_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='class_supervised',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.classes'),
        ),
    ]
