# Generated by Django 4.1.1 on 2022-09-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_teachers_class_supervised'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='timetable_element',
            managers=[
            ],
        ),
    ]
