# Generated by Django 4.1.1 on 2022-09-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_timetable_element_classroom_availability'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timetable_element',
            name='classroom_availability',
        ),
        migrations.AddConstraint(
            model_name='timetable_element',
            constraint=models.UniqueConstraint(fields=('date', 'hour', 'classroom'), name='classroom_availability'),
        ),
    ]
