# Generated by Django 4.1.1 on 2022-10-01 15:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0012_timetable_element_classes_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(help_text='Only numbers and capital letters', max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z]*$', 'Only caps and numbers are allowed.')]),
        ),
    ]
