# Generated by Django 4.1.1 on 2022-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_teachers_user_id_alter_classes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='user_id',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
