# Generated by Django 4.1.1 on 2022-10-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_teachers_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
