# Generated by Django 4.1.1 on 2022-10-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_teachers_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='classrooms',
            options={'ordering': ['classroom_number']},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['last_name']},
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('user_id', models.IntegerField(null=True)),
                ('class_attended', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.classes')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
