# Generated by Django 4.1.1 on 2022-10-05 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_classes_options_alter_classrooms_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='class_attended',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.classes'),
        ),
    ]
