# Generated by Django 4.1.1 on 2022-10-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_students_class_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable_element',
            name='date',
            field=models.DateField(),
        ),
    ]
