# Generated by Django 4.1.1 on 2022-10-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_timetable_element_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], max_length=15)),
                ('hour', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('is_sub', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.classes')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.classrooms')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.teachers')),
            ],
        ),
        migrations.AddConstraint(
            model_name='students_timetable',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'hour', 'classroom'), name='s_classroom_availability'),
        ),
        migrations.AddConstraint(
            model_name='students_timetable',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'hour', 'classes'), name='s_classes_availability'),
        ),
        migrations.AddConstraint(
            model_name='students_timetable',
            constraint=models.UniqueConstraint(fields=('day_of_week', 'hour', 'teacher'), name='s_teacher_availability'),
        ),
    ]
