# Generated by Django 4.1.1 on 2022-10-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_students_timetable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_timetable',
            name='semester',
            field=models.CharField(choices=[(1, 'Summer'), (2, 'Winter')], max_length=20, null=True),
        ),
    ]
