# Generated by Django 4.1.1 on 2022-10-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_students_timetable_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_timetable',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Summer'), (2, 'Winter')], null=True),
        ),
    ]
