# Generated by Django 4.1.1 on 2022-10-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_alter_students_timetable_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_timetable',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='students_timetable',
            name='is_sub',
        ),
    ]
