# Generated by Django 4.1.1 on 2022-10-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_remove_students_timetable_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['subject_name']},
        ),
    ]
