# Generated by Django 4.1.1 on 2022-10-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_timetable_element_prev_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_timetable',
            name='semester',
        ),
    ]
