# Generated by Django 4.1.1 on 2022-10-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_grades_grade_type_alter_assignment_asgn_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grade',
            field=models.IntegerField(choices=[(6, '6'), (5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')]),
        ),
        migrations.AlterField(
            model_name='students',
            name='lucky_color',
            field=models.CharField(default='red', max_length=15),
        ),
    ]
