# Generated by Django 4.1.1 on 2022-10-25 13:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_alter_grades_grade_alter_students_lucky_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='lucky_color',
            field=models.CharField(default='orange', max_length=15),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('status', models.IntegerField(choices=[(1, 'In progress'), (2, 'Reviewed'), (3, 'Denied')])),
                ('reason', models.CharField(max_length=300, null=True)),
                ('comments', models.CharField(max_length=300, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.teachers')),
            ],
        ),
    ]
