# Generated by Django 4.1.1 on 2022-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_alter_students_lucky_color_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('In progess', 'In progress'), ('Reviewed', 'Reviewed'), ('Denied', 'Denied')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='lucky_color',
            field=models.CharField(default='grey', max_length=15),
        ),
    ]
