# Generated by Django 4.1.1 on 2022-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_alter_absence_status_alter_students_lucky_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='dates',
        ),
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Reviewed', 'Reviewed'), ('Denied', 'Denied')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='lucky_color',
            field=models.CharField(default='yellow', max_length=15),
        ),
    ]
