# Generated by Django 4.1.1 on 2022-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0036_remove_absence_dates_alter_absence_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='lucky_color',
            field=models.CharField(default='white', max_length=15),
        ),
    ]
