# Generated by Django 4.1.1 on 2022-10-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0037_alter_students_lucky_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='lucky_color',
            field=models.CharField(default='red', max_length=15),
        ),
    ]
