# Generated by Django 4.1.1 on 2022-10-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_absence_date_alter_students_lucky_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='students',
            name='lucky_color',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='timetable_element',
            name='is_sub',
            field=models.BooleanField(default=True),
        ),
    ]
